### ISSUE TITLE
Errno 2 while starting RVC Server

### ISSUE THREAD

**Issue by therafal** [SayanoAI/RVC-Studio#19]
I get `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/python /app/api.py --port=5555 --host=0.0.0.0'` when trying to start the RVC Server. RVC Studio is running in a docker container.

Traceback:
```
File "/usr/local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/app/pages/0_RVC_Server.py", line 65, in <module>
    start_server(host=state.host,port=state.port)
File "/app/pages/0_RVC_Server.py", line 31, in start_server
    p = subprocess.Popen(cmd, cwd=BASE_DIR)
File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

There are both api.py in the app dir, and python binary in `/usr/local/bin` inside the container.

**Comment by SayanoAI** [comment]
are you able to run "python /app/api.py --port=5555 --host=0.0.0.0" inside your docker container's terminal?

**Comment by therafal** [comment]
> are you able to run "python /app/api.py --port=5555 --host=0.0.0.0" inside your docker container's terminal?

Nope, am getting
```
unknown args: ['--host=0.0.0.0']
Found GPU NVIDIA GeForce RTX 3090
Use Language: en_US
Traceback (most recent call last):
  File "/app/api.py", line 76, in <module>
    main()
  File "/app/api.py", line 73, in main
    subprocess.call(cmd)
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/python -m uvicorn api:server  --workers=1 --port=5555 --host=0.0.0.0'
```

**Comment by therafal** [comment]
Okay, git pulled. Now everything works.
