### ISSUE TITLE
Cannot use TTS Appears to result in a large error message when attempting

### ISSUE THREAD

**Issue by RustyKit-JohnW** [SayanoAI/RVC-Studio#2]
2023-09-15 19:07:49.805 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\myhom\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "C:\RVCStudio\RVC-Studio\pages\3_Text_to_Speech.py", line 140, in <module>
    state.tts_audio = generate_speech(state.tts_text,speaker=os.path.basename(state.model_name).split(".")[0],method=state.tts_method, device=state.device)
  File "C:\Users\myhom\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 216, in basename
    return split(p)[1]
  File "C:\Users\myhom\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by SayanoAI** [comment]
looks like your model name is None, make sure you have a voice model selected
