### ISSUE TITLE
Small FFmpeg error

### ISSUE THREAD

**Issue by skaba04** [SayanoAI/RVC-Studio#3]
I need to help to fix this error that pops of when i want to train the data:
Traceback (most recent call last):
  File "D:\AI\VoiceUI\RVC-Studio\preprocessing_utils.py", line 72, in pipeline
    audio = load_audio(path, self.sr)
  File "D:\AI\VoiceUI\RVC-Studio\lib\audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

**Comment by skaba04** [comment]
i have another error in the training the future index:
Traceback (most recent call last):
  File "D:\Phython\Api\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "D:\AI\VoiceUI\RVC-Studio\pages\2_Train.py", line 320, in <module>
    train_index(state.exp_dir,state.version,state.sr)
  File "D:\AI\VoiceUI\RVC-Studio\pages\2_Train.py", line 144, in train_index
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by skaba04** [comment]
and now i cant even load a model:
Traceback (most recent call last):
  File "D:\Phython\Api\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "D:\AI\VoiceUI\RVC-Studio\pages\2_Train.py", line 320, in <module>
    train_index(state.exp_dir,state.version,state.sr)
  File "D:\AI\VoiceUI\RVC-Studio\pages\2_Train.py", line 144, in train_index
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
2023-09-17 16:14:09.951 Uncaught app exception
Traceback (most recent call last):
  File "D:\Phython\Api\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "D:\AI\VoiceUI\RVC-Studio\pages\2_Train.py", line 320, in <module>
    train_index(state.exp_dir,state.version,state.sr)
  File "D:\AI\VoiceUI\RVC-Studio\pages\2_Train.py", line 144, in train_index
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by skaba04** [comment]
another error:
File "D:\Phython\Api\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "D:\AI\VoiceUI\RVC-Studio\pages\1_Inference.py", line 209, in <module>
    col2.audio(state.input_instrumental[0],sample_rate=state.input_instrumental[1])
File "D:\Phython\Api\lib\site-packages\streamlit\runtime\metrics_util.py", line 358, in wrapped_func
    result = non_optional_func(*args, **kwargs)
File "D:\Phython\Api\lib\site-packages\streamlit\elements\media.py", line 112, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time, sample_rate)
File "D:\Phython\Api\lib\site-packages\streamlit\elements\media.py", line 416, in marshall_audio
    data = _maybe_convert_to_wav_bytes(data, sample_rate)
File "D:\Phython\Api\lib\site-packages\streamlit\elements\media.py", line 377, in _maybe_convert_to_wav_bytes
    data = _make_wav(cast("npt.NDArray[Any]", data), sample_rate)
File "D:\Phython\Api\lib\site-packages\streamlit\elements\media.py", line 363, in _make_wav
    with io.BytesIO() as fp, wave.open(fp, mode="wb") as waveobj:
File "D:\Phython\Api\lib\wave.py", line 332, in __exit__
    self.close()
File "D:\Phython\Api\lib\wave.py", line 444, in close
    self._ensure_header_written(0)
File "D:\Phython\Api\lib\wave.py", line 467, in _ensure_header_written
    self._write_header(datasize)
File "D:\Phython\Api\lib\wave.py", line 479, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',+

**Comment by skaba04** [comment]
I cant even load a model now.

**Comment by SayanoAI** [comment]
> I need to help to fix this error that pops of when i want to train the data: Traceback (most recent call last): File "D:\AI\VoiceUI\RVC-Studio\preprocessing_utils.py", line 72, in pipeline audio = load_audio(path, self.sr) File "D:\AI\VoiceUI\RVC-Studio\lib\audio.py", line 19, in load_audio raise RuntimeError(f"Failed to load audio: {e}") RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

You are missing the ffmpeg.exe executable. Download that from the home page and restart your app

**Comment by skaba04** [comment]
> > I need to help to fix this error that pops of when i want to train the data: Traceback (most recent call last): File "D:\AI\VoiceUI\RVC-Studio\preprocessing_utils.py", line 72, in pipeline audio = load_audio(path, self.sr) File "D:\AI\VoiceUI\RVC-Studio\lib\audio.py", line 19, in load_audio raise RuntimeError(f"Failed to load audio: {e}") RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)
> 
> You are missing the ffmpeg.exe executable. Download that from the home page and restart your app

already done that and the problem is still occuring. I installed that manually.

**Comment by SayanoAI** [comment]
Unfortunately, I was unable to reproduce your error on my machine. You might have a corrupted installation so you will have to reinstall the app.

First do a "git pull" so you have the latest version of the repo.

If you have conda installed and added to your path, you can click "conda-install.bat" to install all the requirements. Otherwise you can run "conda-installer.bat" to automatically install conda and set up the environment for you.

**Comment by skaba04** [comment]
> Unfortunately, I was unable to reproduce your error on my machine. You might have a corrupted installation so you will have to reinstall the app.
> 
> First do a "git pull" so you have the latest version of the repo.
> 
> If you have conda installed and added to your path, you can click "conda-install.bat" to install all the requirements. Otherwise you can run "conda-installer.bat" to automatically install conda and set up the environment for you.

My Antivirus blocked the program

**Comment by SayanoAI** [comment]
> My Antivirus blocked the program

Which program? conda-installer.bat or conda-start.bat? What did your antivirus complain about?

**Comment by skaba04** [comment]
> > My Antivirus blocked the program
> 
> Which program? conda-installer.bat or conda-start.bat? What did your antivirus complain about?

I successfully installed all things and it is working but there is this error again.
Traceback (most recent call last):
  File "D:\AI\VoiceUI\RVC-Studio\preprocessing_utils.py", line 72, in pipeline
    audio = load_audio(path, self.sr)
  File "D:\AI\VoiceUI\RVC-Studio\lib\audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

./datasets/AI_Anis.wav->Suc.

**Comment by SayanoAI** [comment]
if you're using windows, try uninstalling the ffmpeg you manually installed (and remove it from PATH) and use the ffmpeg.exe included in the app (download from Home page)
