### ISSUE TITLE
Error while entering the inference tab

### ISSUE THREAD

**Issue by Pocholo95** [SayanoAI/RVC-Studio#9]
2023-09-23 18:23:43.056 Uncaught app exception
Traceback (most recent call last):
  File "E:\conda-envs\RVC-Studio\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "E:\RVC-Studio\pages\1_Inference.py", line 166, in <module>
    disabled=not (state.uvr5_params.model_paths and state.input_audio_name and state.model_name)):
AttributeError: 'NoneType' object has no attribute 'model_paths'

I already reinstalled and it still doesn't work.
All other tabs work fine.
![imagen_2023-09-23_182735185](https://github.com/SayanoAI/RVC-Studio/assets/42631241/2b65c0ce-acfc-48cf-9de4-f79ef6788122)

**Comment by SayanoAI** [comment]
try the path

**Comment by Pocholo95** [comment]
It works now, thanks
